#!/usr/bin/env python
#
# Copyright (c) 2017      Amazon.com, Inc. or its affiliates.  All Rights
#                         Reserved.
#
# Additional copyrights may follow
#

import OMPIBuilder
import S3BuildFiler


nightly_prefix='/mnt/data/nightly-tarball'
config_data = { 'project_name' : 'PRRTE',
                'project_short_name' : 'prrte',
                'email_dest' : 'bbarrett@amazon.com',
                'email_from' : 'mpiteam@aws.open-mpi.org',
                'repository' : 'https://github.com/pmix/prrte.git',
                'scratch_path' : nightly_prefix + '/scratch',
                'failed_build_prefix' : 'failed-builds/',
                'failed_build_url' : 'http://download.open-mpi.org/nightly/prrte/',
                'autogen' : './autogen.pl',
                'coverity' : { 'tool_dir' : nightly_prefix + '/coverity',
                               'tool_url' : 'https://scan.coverity.com/download/cxx/linux64',
                               'token_file' : nightly_prefix + '/coverity/prrte-token.txt',
                               'project_name' : 'open-mpi%2Fprrte',
                               'project_prefix' : 'prrte',
                               'configure_args' : '',
                               'make_args' : '-j 8',
                               'email' : 'rhc@open-mpi.org' },
                'branches' : { 'master' : { 'output_location' : 'master/',
                                            'coverity' : False,
                                            'max_count' : 7 },
                               },
                }


filer = S3BuildFiler.S3BuildFiler('open-mpi-nightly', 'nightly/prrte/')
builder = OMPIBuilder.OMPIBuilder(config_data, filer)
builder.run()
